import {
  ENEMY_SKILL_LIBRARY_GLOBAL_KEY,
  type EnemyRoleSkillLibrary,
  type EnemySkillLibraryPayload,
} from '../共享/战斗技能';

export const ENEMY_ROLE_SKILLS: EnemyRoleSkillLibrary = {
  guard: [
    {
      id: 'guard_shield_bash',
      name: '盾击',
      kind: 'physical',
      ratio: 1.2,
      cooldown: 1,
      targetType: 'opponent',
      targetMode: 'selected',
      description: '对单体造成 120% 物理伤害。',
    },
    {
      id: 'guard_iron_crash',
      name: '钢铁冲撞',
      kind: 'physical',
      ratio: 1.8,
      cooldown: 2,
      targetType: 'opponent',
      targetMode: 'selected',
      selfDefenseBuffRate: 0.1,
      description: '对单体造成 180% 物理伤害，自身本回合双抗 +10%。',
    },
    {
      id: 'guard_counter_wall',
      name: '反击壁垒',
      cooldown: 3,
      targetType: 'none',
      targetMode: 'none',
      counterStance: true,
      counterIncomingDamageMultiplier: 0.8,
      counterReflectRate: 0.3,
      counterNextRoundHealMaxHpRate: 0.12,
      description: '本回合承伤 80%，返还 30% 法术伤害；下一回合回复 12% 最大生命。',
    },
    {
      id: 'guard_line_lock',
      name: '战线封锁',
      kind: 'physical',
      ratio: 1,
      cooldown: 2,
      targetType: 'opponent',
      targetMode: 'selected',
      silenceNextRound: true,
      description: '对单体造成 100% 物理伤害，并使其下回合沉默。',
    },
    {
      id: 'guard_bulwark_array',
      name: '厚盾护阵',
      cooldown: 3,
      targetType: 'none',
      targetMode: 'none',
      teamShieldMaxHpRate: 0.15,
      description: '为敌方全体附加 15% 最大生命护盾，下一回合开始清除。',
    },
    {
      id: 'guard_armor_breaker',
      name: '破甲重砸',
      kind: 'physical',
      ratio: 1.6,
      cooldown: 2,
      targetType: 'opponent',
      targetMode: 'selected',
      ignoreResistRate: 0.3,
      description: '对单体造成 160% 物理伤害，忽略 30% 物抗。',
    },
    {
      id: 'guard_taunt_cut',
      name: '嘲锋斩',
      kind: 'physical',
      ratio: 1.3,
      cooldown: 2,
      targetType: 'opponent',
      targetMode: 'selected',
      selfDefenseBuffRate: 0.1,
      description: '对单体造成 130% 物理伤害，自身本回合双抗 +10%。',
    },
    {
      id: 'guard_last_guard',
      name: '濒死守护',
      cooldown: 3,
      targetType: 'ally',
      targetMode: 'selected',
      targetHealMaxHpRate: 0.18,
      description: '治疗己方当前生命最低者 18% 最大生命。',
    },
    {
      id: 'guard_quake',
      name: '裂地震击',
      kind: 'physical',
      ratio: 0.55,
      cooldown: 3,
      targetType: 'opponent',
      targetMode: 'allOpponents',
      description: '对敌方全体造成 55% 物理伤害。',
    },
    {
      id: 'guard_crushing_chase',
      name: '碾压追击',
      kind: 'physical',
      ratio: 1.5,
      cooldown: 2,
      targetType: 'opponent',
      targetMode: 'selected',
      executeThresholdHpRate: 0.4,
      executeRatio: 2.1,
      description: '对单体造成 150% 物理伤害；目标生命低于 40% 时改为 210%。',
    },
    {
      id: 'guard_rotate_order',
      name: '换防号令',
      cooldown: 3,
      targetType: 'none',
      targetMode: 'none',
      nextRoundTeamStatBuffRate: 0.1,
      description: '敌方全体下回合除生命外全属性 +10%。',
    },
    {
      id: 'guard_stonewall',
      name: '不动城墙',
      cooldown: 3,
      targetType: 'none',
      targetMode: 'none',
      counterStance: true,
      counterIncomingDamageMultiplier: 0.65,
      counterReflectRate: 0,
      description: '本回合自身承伤降低至 65%。',
    },
  ],
  mage: [
    {
      id: 'mage_fire_lance',
      name: '炎枪术',
      kind: 'magic',
      ratio: 1.2,
      cooldown: 1,
      targetType: 'opponent',
      targetMode: 'selected',
      description: '对单体造成 120% 法术伤害。',
    },
    {
      id: 'mage_arcane_burst',
      name: '奥术爆裂',
      kind: 'magic',
      ratio: 1.9,
      cooldown: 2,
      targetType: 'opponent',
      targetMode: 'selected',
      description: '对单体造成 190% 法术伤害。',
    },
    {
      id: 'mage_frost_spike',
      name: '霜锥',
      kind: 'magic',
      ratio: 1.4,
      cooldown: 2,
      targetType: 'opponent',
      targetMode: 'selected',
      silenceNextRound: true,
      description: '对单体造成 140% 法术伤害，并使其下回合沉默。',
    },
    {
      id: 'mage_meteor_fall',
      name: '陨星落',
      kind: 'magic',
      ratio: 0.65,
      cooldown: 3,
      targetType: 'opponent',
      targetMode: 'allOpponents',
      description: '对敌方全体造成 65% 法术伤害。',
    },
    {
      id: 'mage_overload_core',
      name: '魔力过载',
      kind: 'magic',
      ratio: 2.8,
      cooldown: 3,
      targetType: 'opponent',
      targetMode: 'selected',
      selfOverloadDebuff: true,
      description: '对单体造成 280% 法术伤害；自身进入过载负荷。',
    },
    {
      id: 'mage_piercing_spell',
      name: '穿盾咒',
      kind: 'magic',
      ratio: 1.5,
      cooldown: 2,
      targetType: 'opponent',
      targetMode: 'selected',
      ignoreResistRate: 0.4,
      description: '对单体造成 150% 法术伤害，忽略 40% 法抗。',
    },
    {
      id: 'mage_twin_rift',
      name: '双星裂',
      kind: 'magic',
      ratio: 1.35,
      cooldown: 3,
      targetType: 'opponent',
      targetMode: 'randomOpponents',
      randomTargetCount: 2,
      description: '随机攻击两名敌人，各造成 135% 法术伤害。',
    },
    {
      id: 'mage_void_brand',
      name: '虚空灼印',
      kind: 'magic',
      ratio: 1,
      cooldown: 2,
      targetType: 'opponent',
      targetMode: 'selected',
      targetVulnerableNextRoundRate: 0.1,
      description: '对单体造成 100% 法术伤害，并使其下回合受到伤害 +10%。',
    },
    {
      id: 'mage_silence_ring',
      name: '静默环',
      cooldown: 3,
      targetType: 'opponent',
      targetMode: 'randomOpponents',
      randomTargetCount: 2,
      silenceNextRound: true,
      description: '随机使两名敌人下回合沉默。',
    },
    {
      id: 'mage_arcane_reflow',
      name: '秘法回流',
      cooldown: 3,
      targetType: 'ally',
      targetMode: 'selected',
      cooldownReduction: 1,
      attackBuffRate: 0.2,
      description: '为己方魔攻最高者冷却 -1，并使其攻击 +20%。',
    },
    {
      id: 'mage_spark_volley',
      name: '星火连弹',
      kind: 'magic',
      ratio: 0.9,
      cooldown: 1,
      targetType: 'opponent',
      targetMode: 'selected',
      description: '对单体造成 90% 法术伤害。',
    },
    {
      id: 'mage_end_spell_core',
      name: '终局咒核',
      kind: 'magic',
      ratio: 3.2,
      cooldown: 3,
      targetType: 'opponent',
      targetMode: 'selected',
      ignoreResistRate: 0.2,
      description: '对单体造成 320% 法术伤害，忽略 20% 法抗。',
    },
  ],
  support: [
    {
      id: 'support_light_bolt',
      name: '辉光箭',
      kind: 'magic',
      ratio: 0.9,
      cooldown: 1,
      targetType: 'opponent',
      targetMode: 'selected',
      description: '对单体造成 90% 法术伤害。',
    },
    {
      id: 'support_judgment',
      name: '裁决光束',
      kind: 'magic',
      ratio: 1.5,
      cooldown: 2,
      targetType: 'opponent',
      targetMode: 'selected',
      selfHealMaxHpRate: 0.08,
      description: '对单体造成 150% 法术伤害，并回复自身 8% 最大生命。',
    },
    {
      id: 'support_holy_pulse',
      name: '圣息脉冲',
      cooldown: 3,
      targetType: 'none',
      targetMode: 'none',
      teamHealMaxHpRate: 0.1,
      description: '敌方全体回复 10% 最大生命。',
    },
    {
      id: 'support_grace_mark',
      name: '恩典刻印',
      cooldown: 2,
      targetType: 'ally',
      targetMode: 'selected',
      cooldownReduction: 1,
      attackBuffRate: 0.2,
      description: '指定己方冷却 -1，并使其攻击 +20%。',
    },
    {
      id: 'support_light_screen',
      name: '光幕护佑',
      cooldown: 3,
      targetType: 'none',
      targetMode: 'none',
      teamShieldMaxHpRate: 0.12,
      description: '敌方全体获得 12% 最大生命护盾。',
    },
    {
      id: 'support_silence_prayer',
      name: '禁言祷词',
      kind: 'magic',
      ratio: 0.5,
      cooldown: 3,
      targetType: 'opponent',
      targetMode: 'selected',
      silenceNextRound: true,
      description: '对单体造成 50% 法术伤害，并使其下回合沉默。',
    },
    {
      id: 'support_reverse_blessing',
      name: '逆转祝福',
      cooldown: 3,
      targetType: 'ally',
      targetMode: 'selected',
      targetHealMaxHpRate: 0.25,
      description: '治疗己方当前生命最低者 25% 最大生命。',
    },
    {
      id: 'support_star_chorus',
      name: '群星协奏',
      cooldown: 3,
      targetType: 'none',
      targetMode: 'none',
      nextRoundTeamStatBuffRate: 0.1,
      description: '敌方全体下回合除生命外全属性 +10%。',
    },
    {
      id: 'support_absolve_spark',
      name: '赦免火花',
      kind: 'magic',
      ratio: 1.1,
      cooldown: 2,
      targetType: 'opponent',
      targetMode: 'selected',
      selfHealMaxHpRate: 0.1,
      description: '对单体造成 110% 法术伤害，并回复自身 10% 最大生命。',
    },
    {
      id: 'support_tactical_chant',
      name: '战术清唱',
      cooldown: 2,
      targetType: 'ally',
      targetMode: 'selected',
      cooldownReduction: 1,
      description: '为己方速度最高者冷却 -1。',
    },
    {
      id: 'support_martyr_light',
      name: '殉光裁定',
      kind: 'magic',
      ratio: 1.8,
      cooldown: 3,
      targetType: 'opponent',
      targetMode: 'selected',
      selfCurrentHpCostRate: 0.08,
      teamHealMaxHpRate: 0.08,
      description: '对单体造成 180% 法术伤害，自身损失 8% 当前生命，敌方全体回复 8% 最大生命。',
    },
    {
      id: 'support_balance_art',
      name: '天秤术',
      kind: 'magic',
      ratio: 0.8,
      cooldown: 3,
      targetType: 'any',
      targetMode: 'selected',
      targetHealMaxHpRate: 0.18,
      description: '选敌人造成 80% 法术伤害；选己方回复 18% 最大生命。',
    },
  ],
  assassin: [
    {
      id: 'assassin_backstab',
      name: '背刺',
      kind: 'physical',
      ratio: 1.3,
      cooldown: 1,
      targetType: 'opponent',
      targetMode: 'selected',
      description: '对单体造成 130% 物理伤害。',
    },
    {
      id: 'assassin_shadow_combo',
      name: '影连斩',
      kind: 'physical',
      ratio: 1.9,
      cooldown: 2,
      targetType: 'opponent',
      targetMode: 'selected',
      description: '对单体造成 190% 物理伤害。',
    },
    {
      id: 'assassin_poison_edge',
      name: '毒刃',
      kind: 'physical',
      ratio: 1.2,
      cooldown: 2,
      targetType: 'opponent',
      targetMode: 'selected',
      targetVulnerableNextRoundRate: 0.1,
      description: '对单体造成 120% 物理伤害，并使其下回合受到伤害 +10%。',
    },
    {
      id: 'assassin_execute',
      name: '处决',
      kind: 'physical',
      ratio: 2.6,
      cooldown: 3,
      targetType: 'opponent',
      targetMode: 'selected',
      executeThresholdHpRate: 0.35,
      executeRatio: 3.2,
      description: '对单体造成 260% 物理伤害；目标生命低于 35% 时改为 320%。',
    },
    {
      id: 'assassin_vanish_cut',
      name: '隐袭',
      kind: 'physical',
      ratio: 1,
      cooldown: 2,
      targetType: 'opponent',
      targetMode: 'selected',
      selfUntargetableNextRound: true,
      description: '对单体造成 100% 物理伤害，自身下回合不可被选中。',
    },
    {
      id: 'assassin_overlimit_kill',
      name: '破限绝杀',
      kind: 'physical',
      ratio: 3,
      cooldown: 3,
      targetType: 'opponent',
      targetMode: 'selected',
      selfOverloadDebuff: true,
      description: '对单体造成 300% 物理伤害；自身进入过载负荷。',
    },
    {
      id: 'assassin_armor_pierce',
      name: '穿甲刺',
      kind: 'physical',
      ratio: 1.6,
      cooldown: 2,
      targetType: 'opponent',
      targetMode: 'selected',
      ignoreResistRate: 0.35,
      description: '对单体造成 160% 物理伤害，忽略 35% 物抗。',
    },
    {
      id: 'assassin_backline_cut',
      name: '切后排',
      kind: 'physical',
      ratio: 1.7,
      cooldown: 2,
      targetType: 'opponent',
      targetMode: 'selected',
      targetPriorityRoles: ['mage', 'support'],
      description: '优先攻击法师或辅助，造成 170% 物理伤害。',
    },
    {
      id: 'assassin_dual_raid',
      name: '双刃突袭',
      kind: 'physical',
      ratio: 1.2,
      cooldown: 3,
      targetType: 'opponent',
      targetMode: 'randomOpponents',
      randomTargetCount: 2,
      description: '随机攻击两名敌人，各造成 120% 物理伤害。',
    },
    {
      id: 'assassin_breath_steal',
      name: '夺息',
      kind: 'physical',
      ratio: 1.4,
      cooldown: 2,
      targetType: 'opponent',
      targetMode: 'selected',
      selfHealMaxHpRate: 0.08,
      description: '对单体造成 140% 物理伤害，自身回复 8% 最大生命。',
    },
    {
      id: 'assassin_shadow_rest',
      name: '影遁调息',
      cooldown: 3,
      targetType: 'none',
      targetMode: 'none',
      selfUntargetableNextRound: true,
      selfHealMaxHpRate: 0.12,
      description: '自身下回合不可被选中，并回复 12% 最大生命。',
    },
    {
      id: 'assassin_red_line',
      name: '红线标定',
      kind: 'physical',
      ratio: 0.8,
      cooldown: 3,
      targetType: 'opponent',
      targetMode: 'selected',
      silenceNextRound: true,
      description: '对单体造成 80% 物理伤害，并使其下回合沉默。',
    },
  ],
};

export const ENEMY_SKILL_LIBRARY: EnemySkillLibraryPayload = {
  version: 1,
  roleSkills: ENEMY_ROLE_SKILLS,
};

function registerEnemySkillLibrary() {
  const runtime = window as Window & typeof globalThis & Record<string, unknown>;
  runtime[ENEMY_SKILL_LIBRARY_GLOBAL_KEY] = ENEMY_SKILL_LIBRARY;
}

registerEnemySkillLibrary();
